                                                                                                                                                                                                                                                                                    import pandas as pd
                                                                                                                                                                                                                                                                                    import numpy as np
                                                                                                                                                                                                                                                                                    from datetime import datetime
                                                                                                                                                                                                                                                                                    path = "files/1425challenge.xlsx"
                                                                                                                                                                                                                                                                                    input = pd.read_excel(path,  usecols="B:D", skiprows=2, nrows=4)
                                                                                                                                                                                                                                                                                    test = pd.read_excel(path, usecols="F:G", skiprows=2, nrows=4).rename(columns=lambda x: x.rstrip('.1'))

                                                                                                                                                                                                                                                                                    input[['start_month', 'start_year']] = input['Start'].str.extract(r'^M(\d{2})-(\d{4})')
                                                                                                                                                                                                                                                                                    input[['end_month', 'end_year']] = input['End'].str.extract(r'^M(\d{2})-(\d{4})')
                                                                                                                                                                                                                                                                                    input['start'] = pd.to_datetime(input['start_year'] + '-' + input['start_month'] + '-01')
                                                                                                                                                                                                                                                                                    input['end'] = pd.to_datetime(input['end_year'] + '-' + input['end_month'] + '-01')
                                                                                                                                                                                                                                                                                    input = input.drop(columns=['start_month', 'start_year', 'end_month', 'end_year'])
                                                                                                                                                                                                                                                                                    input['months'] = input.apply(lambda row: pd.date_range(row['start'], row['end'], freq='MS'), axis=1)
                                                                                                                                                                                                                                                                                    input = input.explode('months')
                                                                                                                                                                                                                                                                                    input['res'] = [
                                                                                                                                                                                                                                                                                        row['Start'] if month == row['start'] else (
                                                                                                                                                                                                                                                                                            row['End'] if month == row['end'] else month.strftime('M%m-%Y')
                                                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                                                        for _, row in input.iterrows() for month in [row['months']]
                                                                                                                                                                                                                                                                                    ]
                                                                                                                                                                                                                                                                                    result = input.groupby('Project').agg(
                                                                                                                                                                                                                                                                                        Periods=('res', lambda x: '; '.join(x))
                                                                                                                                                                                                                                                                                    ).reset_index()

                                                                                                                                                                                                                                                                                    print(test.equals(result)) # True